config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  resources :items do 
    resource :favorite, only: [:create, :destroy]
    resources :pictures, only: [:create]
  end
  resources :favorites, only: [:index]
  resources :categories
  resources :types
  resources :carts, only: [:show, :update]
  resources :orders, only: [:index, :create, :show]
  resources :order_items, only: [:index]
  resources :cart_items, only: [:create, :update, :destroy]
  resources :searches, only: [:index]
  resources :new_items, only: [:index]
  resources :charges

  resources :admins, only: [:index, :edit, :update, :destroy]
   # Admin dashboard
  namespace :admins do
    root to: "admins#index"
    resources :users
    resources :items 
    resources :item_sizes
    resources :types
    resources :categories
    
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
	has_many :item_sizes, through: :cart_items

	def total_cart_price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item_size
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :type
	belongs_to :category

	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many :orders, through: :order_items
	has_many :favorites
	has_many :users, through: :favorites
	has_many :item_sizes
	has_many :sizes, through: :item_sizes
	has_one_attached :picture
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
	validates :item_id, presence: true
	validates :size_id, presence: true
	belongs_to :item, dependent: :destroy
	belongs_to :size

	def remove_stock(number)
		self.update(stock: self.stock - number)
	end

	def add_stock(number)
	self.update(stock: self.stock + number)
	end

	def find_item
		Item.find_by(id: self.item_id)	
	end

	def find_size
		self.size.name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items
	has_many :item_sizes, through: :order_items

		def price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order 
	belongs_to :item_size

end

app/models/size.rb
class Size < ApplicationRecord
	has_many :item_sizes
	has_many :items, through: :item_sizes
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
  has_many :favorites
  has_many :items, through: :favorites, dependent: :destroy

  # We launch a method after the creation of the user
  after_create :assign_cart
   # The method assign_cart automatically creates a cart assigned to the used
   def assign_cart 
     Cart.create(user_id: self.id)
   end 

  def favorite(item)
    Favorite.find_or_create_by!(item: item, user_id: self.id)
  end

  def unfavorite(item)
    Favorite.where(item: item, user_id: self.id).destroy_all

    item.reload
  end

  def favorited?(item)
    Favorite.find_by(item_id: item.id, user_id: self.id).present?
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_dashboard.html.erb
<!-- Dashboard menu -->
<div class="col-sm-12 col-md-3 p-3 mb-3 ">
    <div class="row">
        <div class="col">
            <h5 class= "mb-3 p-0">Dashboard administrateur</h5>
            <ul class="list-group-flush p-0 m-0">
                <li class="list-group-item bg-transparent px-0">
                   <i class="fas fa-home text-primary"></i> <%=link_to "Accueil", admins_path, class: 'text-default' %> 
               </li>
               <li class="list-group-item bg-transparent border-bottom px-0">
                  <i class="fas fa-user-friends text-primary"></i> <%=link_to "Utilisateurs", admins_users_path, class: 'text-default' %>
              </li>               
              <li class="list-group-item bg-transparent border-bottom px-0">
                  <i class="fas fa-tshirt text-primary"></i> <%=link_to "Articles", admins_items_path, class: 'text-default' %>
              </li>  
              <li class="list-group-item bg-transparent border-bottom px-0">
                  <i class="fab fa-black-tie text-primary"></i> <%=link_to "Types", admins_types_path, class: 'text-default' %>
              </li>
              <li class="list-group-item bg-transparent border-bottom px-0">
                  <i class="fas fa-transgender-alt text-primary"></i> <%=link_to "Catégories", admins_categories_path, class: 'text-default' %>
              </li>

          </ul>
      </div>
    </div>
</div>

app/views/admins/index.html.erb
<div class="container mt-3">
	<div class="row">
		<!-- Partial for the dashboard menu -->
			<%= render 'admins/dashboard' %>
	</div>
</div>
			