config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  resources :items do 
    resource :favorite, only: [:create, :destroy]
    resources :pictures, only: [:create]
  end
  resources :favorites, only: [:index]
  resources :categories
  resources :types
  resources :carts, only: [:show, :update]
  resources :orders, only: [:index, :create, :show]
  resources :order_items, only: [:index]
  resources :cart_items, only: [:create, :update, :destroy]
  resources :searches, only: [:index]
  resources :new_items, only: [:index]
  resources :charges

  resources :admins, only: [:index, :edit, :update, :destroy]
   # Admin dashboard
  namespace :admins do
    root to: "admins#index"
    resources :users
    resources :items 
    resources :item_sizes
    resources :types
    resources :categories
    
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
	has_many :item_sizes, through: :cart_items

	def total_cart_price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item_size
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :type
	belongs_to :category

	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many :orders, through: :order_items
	has_many :favorites
	has_many :users, through: :favorites
	has_many :item_sizes
	has_many :sizes, through: :item_sizes
	has_one_attached :picture
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
	validates :item_id, presence: true
	validates :size_id, presence: true
	belongs_to :item, dependent: :destroy
	belongs_to :size

	def remove_stock(number)
		self.update(stock: self.stock - number)
	end

	def add_stock(number)
	self.update(stock: self.stock + number)
	end

	def find_item
		Item.find_by(id: self.item_id)	
	end

	def find_size
		self.size.name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items
	has_many :item_sizes, through: :order_items

		def price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order 
	belongs_to :item_size

end

app/models/size.rb
class Size < ApplicationRecord
	has_many :item_sizes
	has_many :items, through: :item_sizes
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
  has_many :favorites
  has_many :items, through: :favorites, dependent: :destroy

  # We launch a method after the creation of the user
  after_create :assign_cart
   # The method assign_cart automatically creates a cart assigned to the used
   def assign_cart 
     Cart.create(user_id: self.id)
   end 

  def favorite(item)
    Favorite.find_or_create_by!(item: item, user_id: self.id)
  end

  def unfavorite(item)
    Favorite.where(item: item, user_id: self.id).destroy_all

    item.reload
  end

  def favorited?(item)
    Favorite.find_by(item_id: item.id, user_id: self.id).present?
  end
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
	before_action :authenticate_user!
	before_action :check_if_admin

		def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(sex: params[:sex])
		if @category.save
			redirect_to admins_categories_path
			flash[:success] = "La nouvelle catégorie a bien été créée"
		else
			flash[:alert] = "Un problème est survenu, veuillez réessayer"
			render :new
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(sex: params[:sex])
			redirect_to admins_categories_path
			flash[:success] = "Les modifications ont bien été enregistrées"
		else
			flash[:alert]= "Un problème est survenu, veuillez réessayer"
			render :edit
		end
		
	end

	def destroy
		@category = Category.find(params[:id])
		if @category.destroy
			redirect_to admins_categories_path
			flash[:success] = "La catégorie a bien été supprimée"
		else
			flash[:alert]= "Un problème est survenu, veuillez réessayer"
			render :edit
		end	
	end

	def check_if_admin
		if current_user.is_admin == false
			flash[:error] = "Vous n'êtes pas un administrateur !"
			redirect_to root_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@items = Item.where.not(type_id: Type.where(name: "chaussures")).where.not(type_id: Type.where(name: "accessoires"))
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/categories/edit.html.erb
<div class="container mt-3">
	<div class="row">
		<%= render 'admins/dashboard' %>
		<div class="colcol-6 mx-auto">

			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'update'), method: 'put' do %>
			<%= label_tag 'Nom' %>
			<%= text_field_tag 'sex', @category.sex, class: "form-control mb-3" %>
			<%= submit_tag "Enregistrer les modifications", class: "btn btn-dark" %>
			<%end%>
			
		</div>
	</div>
	
</div>

app/views/admins/categories/index.html.erb
<div class="container mt-3">
	<div class="row">
		<!-- Partial for the dashboard -->
		<%= render 'admins/dashboard' %>
		<!-- Main content -->
		<div class="col-sm-12 col-md-9">
			<div class="container">
				<div class="row">
						<div class="col">
							<h4 class="p-2 bg-primary-alt"><i class="fas fa-transgender-alt text-primary"></i> Catégories</h4>
						</div>
					</div>
				<div class="row">
					<div class="col mx-2 mb-3">
						<%= link_to "Créer une nouvelle catégorie", new_admins_category_path, class: "btn btn btn-primary" %>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<% @categories.order(sex: :asc).each do |category|%>
						<ul class="list-group">
							<%= link_to edit_admins_category_path(category) do %>
							<li class="list-group-item d-flex justify-content-between align-items-center">
								
								<%= category.sex%> <%= link_to "Supprimer", admins_category_path(category), method: :delete, data: { confirm: 'Êtes-vous sûr.e ?' }, class: "btn btn-sm btn-danger ml-3" %>
							</li><%end%>
						</ul>
						<%end%>
					</div>
				</div>
			</div>
		</div>	
	</div>
</div>

app/views/admins/categories/new.html.erb
<div class="container mt-3">
	<div class="row">
		<%= render 'admins/dashboard' %>
		<div class="col col-6 mx-auto">

			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'create'), method: 'post' do %>

			<%= label_tag 'Nom' %>
			<%= text_field_tag 'sex', @category.sex, class: "form-control mb-3" %>

			<%= submit_tag "Créer la nouvelle catégorie", class: "btn btn-dark" %>
			<%end%>
			
		</div>
	</div>
	
</div>

app/views/categories/index.html.erb
<div class="container girl-bg">
	<div class="row mt-5 mb-4">
		<%= render 'layouts/index' %>
	</div>
</div>		