config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  resources :items do 
    resource :favorite, only: [:create, :destroy]
    resources :pictures, only: [:create]
  end
  resources :favorites, only: [:index]
  resources :categories
  resources :types
  resources :carts, only: [:show, :update]
  resources :orders, only: [:index, :create, :show]
  resources :order_items, only: [:index]
  resources :cart_items, only: [:create, :update, :destroy]
  resources :searches, only: [:index]
  resources :new_items, only: [:index]
  resources :charges

  resources :admins, only: [:index, :edit, :update, :destroy]
   # Admin dashboard
  namespace :admins do
    root to: "admins#index"
    resources :users
    resources :items 
    resources :item_sizes
    resources :types
    resources :categories
    
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
	has_many :item_sizes, through: :cart_items

	def total_cart_price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item_size
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :type
	belongs_to :category

	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many :orders, through: :order_items
	has_many :favorites
	has_many :users, through: :favorites
	has_many :item_sizes
	has_many :sizes, through: :item_sizes
	has_one_attached :picture
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
	validates :item_id, presence: true
	validates :size_id, presence: true
	belongs_to :item, dependent: :destroy
	belongs_to :size

	def remove_stock(number)
		self.update(stock: self.stock - number)
	end

	def add_stock(number)
	self.update(stock: self.stock + number)
	end

	def find_item
		Item.find_by(id: self.item_id)	
	end

	def find_size
		self.size.name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items
	has_many :item_sizes, through: :order_items

		def price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order 
	belongs_to :item_size

end

app/models/size.rb
class Size < ApplicationRecord
	has_many :item_sizes
	has_many :items, through: :item_sizes
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
  has_many :favorites
  has_many :items, through: :favorites, dependent: :destroy

  # We launch a method after the creation of the user
  after_create :assign_cart
   # The method assign_cart automatically creates a cart assigned to the used
   def assign_cart 
     Cart.create(user_id: self.id)
   end 

  def favorite(item)
    Favorite.find_or_create_by!(item: item, user_id: self.id)
  end

  def unfavorite(item)
    Favorite.where(item: item, user_id: self.id).destroy_all

    item.reload
  end

  def favorited?(item)
    Favorite.find_by(item_id: item.id, user_id: self.id).present?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	helper_method :current_or_guest_user
	def show
		@cart = Cart.find(params[:id])
				# We want to show the items in the cart only once, so we create a new array
		# without the duplicate entries
		@cart_items = @cart.item_sizes
		@cart_items_unique = @cart_items.uniq
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/new_items_helper.rb
module NewItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container">

	<ul class="list-group list-group-flush mt-4">
		<% @cart_items_unique.each do |item| %>
		<li class="list-group-item">
			<div class="row align-items-center">
				<div class="col col-1">
					<%= image_tag item.find_item.picture, class: 'mr-3 rounded W35', style: "width: 50px; 
  height: auto;" %>
				</div> 
				<div class="col col-8">
					<h5 class="mt-0 mb-1"><%= item.find_item.name %> </h5>
					<%=number_to_currency item.find_item.price, unit: "€", separator: ",", format: "%n%u" %> 
				</div>

				<div class="col col-3 text-right">
					<%= link_to " - ", cart_item_path(:item_size_id => item.id, :add_or_remove => "remove"), controller: 'cart_items', method: "put", action: 'update', class: "btn btn-sm btn-dark mr-1" %>
						<%= CartItem.where(cart_id: @cart.id, item_size_id: item.id).count %>
						<%= link_to "+", cart_item_path(:item_size_id => item.id, :add_or_remove => "add"), controller: 'cart_items', method: "put", action: 'update', class: "btn btn-sm btn-dark ml-1" %>

					<%= link_to "Supprimer", cart_item_path(:item_size_id => item.id), controller: 'cart_items', method: "delete", action: 'destroy', class: "btn btn-warning btn-sm ml-4"%>  
				</div> 
			</div>
		</li>
		<% end %>
	</ul>


	<!-- finalize order button -->
	<div class="row">
		<div class="col">
			<% if @cart.item_sizes.count == 0 %>
			<div class="mt-4 text-center"> 
				<p>Votre panier est vide</p>
				<%= link_to "Retour aux articles", root_path, class: "btn btn-dark mt-3" %>	 
			</div>
			<% elsif user_signed_in?%>
			<div class="mt-4 text-center">  <p> Total: <%= @cart.total_cart_price %> € </p>
			<%= link_to "Passer la commande", new_charge_path(cart_id: @cart.id), class: "btn btn-dark mt-3" %>	
			</div>
			<% else%>
			<p class="text-center mt-4">
				Total: <%= @cart.total_cart_price %> €
			</p>
			<p class="text-center">
				Vous n'êtes pas connecté(e), veuillez: 
			</p>
			<div class="mt-4 text-center align-items-center">  
				<%= link_to "Vous connecter", new_user_session_path, class: "btn btn-dark mr-2" %>	or <%= link_to "Créer un compte", new_user_registration_path, class: "btn btn-dark ml-2" %>	 
			</div>
			<%end%>
		</div>
	</div>


</div>