config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  resources :items do 
    resource :favorite, only: [:create, :destroy]
    resources :pictures, only: [:create]
  end
  resources :favorites, only: [:index]
  resources :categories
  resources :types
  resources :carts, only: [:show, :update]
  resources :orders, only: [:index, :create, :show]
  resources :order_items, only: [:index]
  resources :cart_items, only: [:create, :update, :destroy]
  resources :searches, only: [:index]
  resources :new_items, only: [:index]
  resources :charges

  resources :admins, only: [:index, :edit, :update, :destroy]
   # Admin dashboard
  namespace :admins do
    root to: "admins#index"
    resources :users
    resources :items 
    resources :item_sizes
    resources :types
    resources :categories
    
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
	has_many :item_sizes, through: :cart_items

	def total_cart_price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item_size
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :type
	belongs_to :category

	has_many :cart_items
	has_many :carts, through: :cart_items
	has_many :order_items
	has_many :orders, through: :order_items
	has_many :favorites
	has_many :users, through: :favorites
	has_many :item_sizes
	has_many :sizes, through: :item_sizes
	has_one_attached :picture
end

app/models/item_size.rb
class ItemSize < ApplicationRecord
	validates :item_id, presence: true
	validates :size_id, presence: true
	belongs_to :item, dependent: :destroy
	belongs_to :size

	def remove_stock(number)
		self.update(stock: self.stock - number)
	end

	def add_stock(number)
	self.update(stock: self.stock + number)
	end

	def find_item
		Item.find_by(id: self.item_id)	
	end

	def find_size
		self.size.name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items
	has_many :item_sizes, through: :order_items

		def price
		#We set a counter at 0
		total = 0
		#We iterate through the items in the cart
		self.item_sizes.each do |item|
			#We add the price item at the counter at each iteration of the loop,
			#to obtain the total price
			total+= Item.find(item.item_id).price
		end

		return total
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order 
	belongs_to :item_size

end

app/models/size.rb
class Size < ApplicationRecord
	has_many :item_sizes
	has_many :items, through: :item_sizes
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
  has_many :favorites
  has_many :items, through: :favorites, dependent: :destroy

  # We launch a method after the creation of the user
  after_create :assign_cart
   # The method assign_cart automatically creates a cart assigned to the used
   def assign_cart 
     Cart.create(user_id: self.id)
   end 

  def favorite(item)
    Favorite.find_or_create_by!(item: item, user_id: self.id)
  end

  def unfavorite(item)
    Favorite.where(item: item, user_id: self.id).destroy_all

    item.reload
  end

  def favorited?(item)
    Favorite.find_by(item_id: item.id, user_id: self.id).present?
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_if_admin

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(name: params[:name], price: params[:price], description: params[:description], category: Category.find( params[:category].to_i), type: Type.find(params[:type].to_i))
		@item.picture.attach(params[:picture])
			if @item.save
				redirect_to new_admins_item_size_path(item_id: @item)
				flash[:success] = "L'article a bien été crée"
			else 
				flash[:alert] = "Un problème est survenu, veuillez reessayer"
				render :new
			end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@item.picture.attach(params[:picture])
		if @item.update(name: params[:name], price: params[:price], description: params[:description], category: Category.find(params[:category].to_i), type: Type.find(params[:type].to_i))
			redirect_to admins_items_path
			flash[:success] = "Les modifications ont bien été enregistrées"
		else
			flash[:alert]= "Un problème est survenu, veuillez reessayer"
			render :edit
		end
	end

	def destroy
		@item = Item.find(params[:id])
		if @item.destroy
			redirect_to admins_items_path
			flash[:success] = "L'article a bien été supprimé"
		else
			flash[:alert] = "Un problème est survenu, veuillez reessayer"
		end
	end

	def check_if_admin
		if current_user.is_admin == false
			flash[:error] = "Vous n'êtes pas un administrateur !"
			redirect_to root_path
		end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
	sex = params[:c] # should be all in this case
  @items = Item.where(:category_id => sex)
	end

	def show
		@item = Item.find(params[:id])
		@sizes = Size.all
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/new_items_helper.rb
module NewItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/items/_item_cards_admin_dashboard.html.erb
<!-- Begining of the loop -->
<% @items.order(created_at: :desc).each do |item| %>
<!-- CARD -->

<div class="card row mx-2 o-hidden hover-shadow-3d p-0 mt-0 mb-2">
	<div class="card-body col p-3">
		<div class="flex-grow-1">
			<div class="d-flex align-items-center">
				<div class="ml-2">
					<h5 class="m-0 p-0">
						
						<!-- Name -->
						
						  <%= item_picture(item.id) %> <%= item.name %>  

						
					</h5>
					<!-- Price -->
					<p><%=number_to_currency item.price, unit: "€", separator: ",", format: "%n%u" %>  </p>

					<p> <%= link_to(admins_item_sizes_path(item_id: item.id), class: "btn btn-dark") do %>
						Modifier le nombre d'article en stock
						<% end %>

						<%= link_to(edit_admins_item_path(item.id), class: "btn btn-dark") do %>
						Modifier l'article
						<% end %>

						<%= link_to(admins_item_path(item), method: :delete, data: { confirm: 'Êtes-vous sûr.e ?' }, class: "btn btn-sm btn-danger") do %>
						Supprimer
						<% end %>

					</p> 
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/admins/items/edit.html.erb
<div class="container mt-3">
	<div class="row">
		<div class="colcol-6 mx-auto">

			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'update'), method: 'put', multipart: true do %>

			<%= label_tag 'Photo de l\'article' %>
			<%= file_field_tag :picture, class: "form-control mb-3" %>
  

			<%= label_tag 'Nom de l\'article' %>
			<%= text_field_tag 'name', @item.name, class: "form-control mb-3" %>


			<%= label_tag 'Prix' %>
			<%= number_field_tag 'price', @item.price, min: "1", class: "form-control mb-3" %>

			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', @item.description, class: "form-control mb-3"  %>

			<%= label_tag 'Catégorie :', nil %>
             <%=select_tag(:category, options_from_collection_for_select(Category.all, :id, :sex, selected: @item.category_id), class: "form-control mb-3")%>

            <%= label_tag 'Type :', nil %>

            <%=select_tag(:type, options_from_collection_for_select(Type.all, :id, :name, selected: @item.type_id), class: "form-control mb-3") %>

			<%= submit_tag "Enregistrer les modifications", class: "btn btn-dark" %>
			<%end%>
			
		</div>
	</div>
	
</div>

app/views/admins/items/index.html.erb
<div class="container mt-3">
		<div class="row">
			<!-- Partial for the dashboard -->
			<%= render 'admins/dashboard' %>
			<div class="col-sm-12 col-md-9">
				<div class="container">
					<div class="row">
						<div class="col">
							<h4 class="p-2 bg-primary-alt"><i class="fas fa-tshirt text-primary"></i> Articles</h4>
						</div>
					</div>
					<div class="row">
						<div class="col mx-2 mb-3">
							<%= link_to "Créer un article", new_admins_item_path, class: "btn btn btn-primary" %>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<%= render 'item_cards_admin_dashboard' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/admins/items/new.html.erb
<div class="container mt-3">
	<div class="row">
		<div class="colcol-6 mx-auto">

			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'create'), method: 'post', multipart: true do %>

			<%= label_tag 'Photo de l\'article' %>
			<%= file_field_tag :picture, class: "form-control mb-3" %>
  

			<%= label_tag 'Nom de l\'article' %>
			<%= text_field_tag 'name', @item.name, class: "form-control mb-3" %>


			<%= label_tag 'Prix' %>
			<%= number_field_tag 'price', @item.price, min: "1", class: "form-control mb-3" %>

			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', @item.description, class: "form-control mb-3"  %>

			<%= label_tag 'Catégorie :', nil %>
             <%=select_tag(:category, options_from_collection_for_select(Category.all, :id, :sex), class: "form-control mb-3")%>

            <%= label_tag 'Type :', nil %>

            <%=select_tag(:type, options_from_collection_for_select(Type.all, :id, :name), class: "form-control mb-3") %>

			<%= submit_tag "Créer l'article", class: "btn btn-dark" %>
			<%end%>
			
		</div>
	</div>
	
</div>